CREATE OR REPLACE VIEW VORDERS_STATUS AS(
SELECT 
O.ORDER_ID,
PD.PROD_NAME,
V.VENDOR_NAME,
O.ORDER_STATUS AS ORDER_STATUS,
I.ORDER_STATUS AS LINE_ITEM_STATUS,
C.CUST_ID,
C.CUST_FIRST_NAME ||' ' || C.CUST_LAST_NAME || ' ' || C.CUST_MIDDLE_NAME AS CUSTOMER_NAME
FROM 
CUSTOMER C,
ORDERS O,
LINE_ITEMS I,
VENDOR V,
PRODUCT_DETAILS PD
WHERE C.CUST_ID = O.CUST_ID
AND O.ORDER_ID = I.ORDER_ID
AND I.PROD_DETAIL_ID = PD.PROD_DETAIL_ID
AND PD.VENDOR_ID = V.VENDOR_ID 
-----AND C.CUST_ID = 'CUST-130' 
)
;