 CREATE OR REPLACE  VIEW VPRODUCT_ORDER_DETAILS ("CUST_ID", "CUSTOMER_NAME", "ORDER_ID", "ITEM_ID", "PROD_NAME", "OVERALL_ORDER_STATUS", "LINE_ITEM_STATUS") 
 
  (
SELECT 
C.CUST_ID,
C.CUST_FIRST_NAME ||' ' || C.CUST_LAST_NAME || ' ' || C.CUST_MIDDLE_NAME AS CUSTOMER_NAME,
O.ORDER_ID,
i.item_id ,
PD.PROD_NAME,
O.ORDER_STATUS AS OVERALL_ORDER_STATUS,
I.ORDER_STATUS AS LINE_ITEM_STATUS
FROM 
CUSTOMER C,
ORDERS O,
LINE_ITEMS I,
PRODUCT_DETAILS PD
WHERE C.CUST_ID = O.CUST_ID(+)
AND O.ORDER_ID = I.ORDER_ID(+)
AND i.prod_detail_id = PD.PROD_DETAIL_ID(+)
---AND C.CUST_ID = 'CUST-130' AND O.ORDER_ID = 18
AND UPPER(C.CUST_FIRST_NAME) = ( SELECT USER FROM DUAL )
);