CREATE OR REPLACE TRIGGER CHECK_STOCK_QUANTITY  
  BEFORE INSERT OR UPDATE ON LINE_ITEMS 
  for each row
DECLARE
  VPROD_UNIT_AVAILABLE PRODUCT_DETAILS.PROD_UNIT_AVAILABLE%TYPE;
BEGIN 
  SELECT PROD_UNIT_AVAILABLE 
    INTO VPROD_UNIT_AVAILABLE
    FROM PRODUCT_DETAILS
   WHERE PROD_DETAIL_ID = :NEW.PROD_DETAIL_ID;
  IF(:NEW.QUANTITY > VPROD_UNIT_AVAILABLE) then
    RAISE_APPLICATION_ERROR(-20103, 'STOCK NOT AVAILABLE');
  ELSE
    UPDATE PRODUCT_DETAILS
       SET PROD_UNIT_AVAILABLE = PROD_UNIT_AVAILABLE - :NEW.QUANTITY
     where PROD_DETAIL_ID = :NEW.PROD_DETAIL_ID;
  END IF;
END;
/
EXECUTE PROC_LINE_ITEMS_INSERT ( 1, 'PROD123', 3, 220  );
COMMIT;
INSERT INTO LINE_ITEMS VALUES ( 4, 1, 'PROD123' , 6, 3,4,50,67,'ORDER PLACED'  );