create or replace PROCEDURE PROC_ADD_VENDOR( 
P_VENDOR_NAME IN VARCHAR2,
P_VENDOR_DESC IN VARCHAR2, 
P_CNTRCT_START_DT IN DATE, 
P_CNTRCT_END_DT IN DATE
)
AS
V_CONTRACTID VARCHAR(40) := 'CNTRCT' || TRUNC(DBMS_RANDOM.VALUE(0,1000000));
BEGIN
INSERT INTO VENDOR VALUES ( 
SEQ_VENDOR_ID.NEXTVAL, 
P_VENDOR_NAME,
P_VENDOR_DESC,
P_CNTRCT_START_DT,
P_CNTRCT_END_DT,
'N',
'NEW',
V_CONTRACTID
);
COMMIT;
DBMS_OUTPUT.put_line('NEW VENDOR ADDED');
END;