create or replace PROCEDURE 
PROC_ADD_REVIEWS 
( P_CUST_ID IN reviews.cust_id%TYPE, P_PROD_DETAIL_ID IN reviews.prod_detail_id%TYPE , P_COMMENTS reviews.comments%TYPE, P_RATING reviews.rating%TYPE  )
AS
BEGIN
MERGE INTO REVIEWS USING DUAL ON (CUST_ID = P_CUST_ID AND PROD_DETAIL_ID = P_PROD_DETAIL_ID)
WHEN MATCHED THEN
UPDATE SET COMMENTS = P_COMMENTS,
RATING = P_RATING
WHEN NOT MATCHED THEN 
INSERT VALUES ( SEQ_REVIEW_ID.NEXTVAL,
P_CUST_ID , P_PROD_DETAIL_ID , P_COMMENTS , P_RATING ) ;
COMMIT;
 EXCEPTION
        WHEN OTHERS THEN
            dbms_output.put_line('Please correct the following error - ' || SQLERRM);
END;
