create or replace PROCEDURE PROC_ADD_CUST_CON ( P_ADDR_ID IN NUMBER,
P_CUST_ID IN VARCHAR2, P_ADDRESS_LINE_1 IN VARCHAR2, P_ADDRESS_LINE_2 IN VARCHAR2, P_CITY IN VARCHAR2,
P_STATE IN VARCHAR2, P_REGION VARCHAR2, P_ZIPCODE IN VARCHAR2, P_PHONE_1 IN NUMBER)
AS
BEGIN
MERGE INTO CUST_CONTACT_DETAILS  USING
DUAL ON ( CUST_ID = P_CUST_ID AND ADDRESS_ID = P_ADDR_ID )
WHEN MATCHED THEN
UPDATE SET 
ADDRESS_LINE_1 = P_ADDRESS_LINE_1,
ADDRESS_LINE_2 = P_ADDRESS_LINE_2,
CITY = P_CITY,
CUST_STATE = P_STATE,
ZIPCODE = P_ZIPCODE,
PHONE_1 = P_PHONE_1
WHEN NOT MATCHED THEN 
INSERT VALUES ( 
P_ADDR_ID,
P_CUST_ID,
P_ADDRESS_LINE_1,
P_ADDRESS_LINE_2,
P_CITY,
P_STATE,
P_REGION,
P_ZIPCODE,
P_PHONE_1,
TO_CHAR(SYSTIMESTAMP, 'DD-MON-YYYY HH:MI:SS PM'),
TO_CHAR(TO_DATE('31-DEC-4747','DD-MON-YYYY'), 'DD-MON-YYYY HH:MI:SS PM')
);

COMMIT;
 EXCEPTION
        WHEN OTHERS THEN
            dbms_output.put_line('Please correct the following error - ' || SQLERRM);
END;