create or replace PROCEDURE PROC_ORDER_DETAILS_INSERT(
P_CUST_ID IN VARCHAR2, P_ADDRESS_ID IN NUMBER, 
P_PAYMENT_ID IN NUMBER, P_DELIVERY_MODE VARCHAR2 , P_TOTAL_ITEMS IN NUMBER )
AS
--V_CUST_ID VARCHAR(20);
V_PAYMENT_ID NUMBER;
V_ADDRESS_ID NUMBER;
v_SHIPPINGS_DAYS NUMBER :=  FUNC_CAL_SHIPPING_DAYS(P_DELIVERY_MODE);
BEGIN
INSERT INTO ORDERS VALUES ( SEQ_ORDER_ID.NEXTVAL,
P_CUST_ID,
P_ADDRESS_ID,
SYSDATE,
P_PAYMENT_ID,
P_TOTAL_ITEMS,
v_SHIPPINGS_DAYS,
'ORDER PLACED',
P_DELIVERY_MODE
);
COMMIT;
EXCEPTION
        WHEN OTHERS THEN
            dbms_output.put_line('Please correct the following error - ' || SQLERRM);
            END;
