create or replace PROCEDURE PROC_ADD_VENDOR_ADDRESS ( P_ADDR_ID IN NUMBER,
P_VENDOR_ID IN NUMBER, P_VENDOR_EMAIL IN VARCHAR2, P_ADDRESS_LINE_1 IN VARCHAR2, P_ADDRESS_LINE_2 IN VARCHAR2, P_CITY IN VARCHAR2,
P_STATE IN VARCHAR2, P_ZIPCODE IN VARCHAR2, P_PHONE_1 IN NUMBER)
AS
BEGIN
MERGE INTO VENDOR_ADDRESS  USING
DUAL ON ( VENDOR_ID = P_VENDOR_ID AND VENDOR_ADDRESS_ID = P_ADDR_ID )
WHEN MATCHED THEN
UPDATE SET VENDOR_EMAIL = P_VENDOR_EMAIL,
ADDRESS_LINE_1 = P_ADDRESS_LINE_1,
ADDRESS_LINE_2 = P_ADDRESS_LINE_2,
CITY = P_CITY,
STATE = P_STATE,
ZIPCODE = P_ZIPCODE,
PHONE_1 = P_PHONE_1
WHEN NOT MATCHED THEN 
INSERT VALUES ( 
P_ADDR_ID,
P_VENDOR_ID, 
P_VENDOR_EMAIL,
P_ADDRESS_LINE_1,
P_ADDRESS_LINE_2,
P_CITY,
P_STATE,
P_ZIPCODE,
P_PHONE_1
);
COMMIT;
DBMS_OUTPUT.put_line('NEW VENDOR ADDED');
 EXCEPTION
        WHEN OTHERS THEN
            dbms_output.put_line('Please correct the following error - ' || SQLERRM);
END;
