create or replace PROCEDURE PROC_VENDOR_RENEWAL(
P_VENDORID IN NUMBER,
P_CNTRCT_START_DT IN DATE, 
P_CNTRCT_END_DT  IN DATE )
AS
--V_CNTRCT_START_DT vendor.contract_start_date%TYPE, 
--V_CNTRCT_END_DT  DATE,
VENDOR_REC VENDOR%ROWTYPE;
BEGIN
SELECT * INTO VENDOR_REC 
FROM VENDOR WHERE VENDOR_ID = P_VENDORID;
   IF P_CNTRCT_START_DT <= VENDOR_REC.CONTRACT_END_DATE + 30
   THEN 
    INSERT INTO VENDOR_HISTORY 
     (VENDOR_ID, VENDOR_NAME, VENDOR_DESC, CONTRACT_START_DATE, CONTRACT_END_DATE, IS_RENEWED , CONTRACT_TYPE, CONTRACT_ID)
     (SELECT * FROM VENDOR WHERE VENDOR_ID = P_VENDORID );

   UPDATE vendor SET
   CONTRACT_START_DATE = P_CNTRCT_START_DT,
   CONTRACT_END_DATE = P_CNTRCT_END_DT,
   IS_RENEWED = 'Y',
   CONTRACT_TYPE = 'RENEWED'
     WHERE VENDOR_ID = P_VENDORID;
    DBMS_OUTPUT.PUT_LINE('VENDOR CONTRACT RENEWED');
    END IF;

    IF P_CNTRCT_START_DT > VENDOR_REC.CONTRACT_END_DATE + 30
     THEN DBMS_OUTPUT.PUT_LINE('NEW CONTRACTID AND NEW INSERT IS MADE FOR EXISTING VENDOR IN SYSTEM');
     INSERT INTO VENDOR_HISTORY 
     (VENDOR_ID, VENDOR_NAME, VENDOR_DESC, CONTRACT_START_DATE, CONTRACT_END_DATE, IS_RENEWED , CONTRACT_TYPE, CONTRACT_ID)
     (SELECT * FROM VENDOR WHERE VENDOR_ID = P_VENDORID );

     UPDATE vendor SET
     CONTRACT_START_DATE = P_CNTRCT_START_DT,
     CONTRACT_END_DATE = P_CNTRCT_END_DT,
      IS_RENEWED = 'N',
     CONTRACT_ID = 'CNTRCT' || TRUNC(DBMS_RANDOM.VALUE(0,1000000)),
     CONTRACT_TYPE = 'NEW'
     WHERE VENDOR_ID = P_VENDORID;
    END IF;  

   IF P_CNTRCT_START_DT = VENDOR_REC.CONTRACT_START_DATE AND P_CNTRCT_END_DT = VENDOR_REC.CONTRACT_END_DATE  
       THEN 
       DBMS_OUTPUT.PUT_LINE('NO CHANGES IN THE CONTRACT');
   END IF;

   EXCEPTION WHEN NO_DATA_FOUND
   THEN 
   DBMS_OUTPUT.PUT_LINE('VENDOR NOT FOUND IN SYSTEM');  

END;