create or replace PROCEDURE PROC_INSERT_UPDATE_CUST(P_CUST_ID IN CUSTOMER.CUST_ID%TYPE,
P_FIRST_NAME IN CUSTOMER.CUST_FIRST_NAME%TYPE,
P_LAST_NAME IN CUSTOMER.CUST_LAST_NAME%TYPE,
P_CUST_MIDDLE_NAME IN CUSTOMER.CUST_MIDDLE_NAME%TYPE,
P_CUST_GENDER IN CUSTOMER.CUST_GENDER%TYPE,
P_CUST_MARITAL_STATUS IN CUSTOMER.CUST_MARITAL_STATUS%TYPE,
P_CUST_EMAIL   IN   CUSTOMER.CUST_EMAIL%TYPE,
P_CUST_PASSWORD   IN   CUSTOMER.CUST_PASSWORD%TYPE,  
P_CUST_DOB  IN   CUSTOMER.CUST_DOB%TYPE )
IS 
P_INPUT_HASH_VALUE NUMBER;
P_INPUT_CUST_ID VARCHAR2(20);
F_HASH_VALUE NUMBER;
BEGIN
F_HASH_VALUE := FUNC_CUST_HASH_VALUE1
(
P_CUST_ID ,
P_FIRST_NAME, 
P_LAST_NAME ,
P_CUST_MIDDLE_NAME ,
P_CUST_GENDER,
P_CUST_MARITAL_STATUS, 
P_CUST_EMAIL  ,
P_CUST_PASSWORD,          
P_CUST_DOB 
);
SELECT CUST_ID, HASH_VALUE INTO P_INPUT_CUST_ID , P_INPUT_HASH_VALUE
FROM CUSTOMER WHERE CUST_ID = P_CUST_ID AND TO_CHAR(CUST_EFFECTIVE_TO, 'DD-MON-YYYY') = '31-DEC-4747';
IF P_CUST_ID = P_INPUT_CUST_ID AND F_HASH_VALUE = P_INPUT_HASH_VALUE
THEN DBMS_OUTPUT.PUT_LINE('EXISTING CUSTOMER');
END IF;
IF P_CUST_ID = P_INPUT_CUST_ID AND F_HASH_VALUE <> P_INPUT_HASH_VALUE
THEN 
update CUSTOMER SET 
CUST_ID = P_CUST_ID,
CUST_FIRST_NAME = P_FIRST_NAME,
CUST_LAST_NAME = P_LAST_NAME,
CUST_MIDDLE_NAME = P_CUST_MIDDLE_NAME,
CUST_GENDER = P_CUST_GENDER,
CUST_MARITAL_STATUS = P_CUST_MARITAL_STATUS,
CUST_EMAIL = P_CUST_EMAIL,
CUST_PASSWORD = P_CUST_PASSWORD,
CUST_DOB = P_CUST_DOB,
HASH_VALUE = F_HASH_VALUE
WHERE CUST_ID = P_CUST_ID AND TO_CHAR(CUST_EFFECTIVE_TO, 'DD-MON-YYYY') = '31-DEC-4747';
DBMS_OUTPUT.PUT_LINE('CUSTOMER UPDATED');
END IF;
EXCEPTION
   WHEN NO_DATA_FOUND
THEN 
INSERT INTO CUSTOMER VALUES (
P_CUST_ID,
P_FIRST_NAME,
P_LAST_NAME,
P_CUST_MIDDLE_NAME,
P_CUST_GENDER,
P_CUST_MARITAL_STATUS,
P_CUST_EMAIL,
ora_hash( P_CUST_EMAIL||P_CUST_PASSWORD),
---P_CUST_PASSWORD,
P_CUST_DOB,
TO_CHAR(SYSTIMESTAMP, 'DD-MON-YYYY HH:MI:SS PM'),
TO_CHAR(TO_DATE('31-DEC-4747','DD-MON-YYYY'), 'DD-MON-YYYY HH:MI:SS PM'),
'Y' ,
ora_hash(P_CUST_ID||
P_FIRST_NAME||
P_LAST_NAME||
P_CUST_MIDDLE_NAME||
P_CUST_GENDER||
P_CUST_MARITAL_STATUS||
P_CUST_EMAIL||
P_CUST_PASSWORD||
P_CUST_DOB)
);
COMMIT;
DBMS_OUTPUT.PUT_LINE('NEW CUSTOMER ADDED');
END;