create or replace PROCEDURE PROC_ADD_CUST_PAYMENT (
P_CUST_ID CUSTOMER.CUST_ID%TYPE, 
P_PAYMENT_TYPE CUST_PAYMENT.PAYMENT_TYPE%TYPE, P_CARD_TYPE CUST_PAYMENT.CARD_TYPE%TYPE,
P_CARD_NUMBER CUST_PAYMENT.CARD_NUMBER%TYPE,
P_CARD_EXPIRY_dATE CUST_PAYMENT.CARD_EXPIRY_DATE%TYPE)
AS
V_CUST_ID VARCHAR(20);
--V_PAYMENT_TYPE VARCHAR2(20);
--V_CARD_EXPRIRY_dATE DATE := to_date(to_char(P_CARD_EXPIRY_dATE,'MM/RR'),'MM/RR');
V_CARD_EXPRIRY_dATE VARCHAR(20) :=   to_CHAR(TO_DATE(P_CARD_EXPIRY_dATE,'MM-RRRR'),'MM/RR');
BEGIN
SELECT CUST_ID INTO V_CUST_ID FROM CUSTOMER WHERE CUST_ID = P_CUST_ID;
IF P_PAYMENT_TYPE = 'CREDIT CARD' OR P_PAYMENT_TYPE = 'DEBIT CARD'
THEN
INSERT INTO CUST_PAYMENT
VALUES ( 
SEQ_PAYMENT_ID.NEXTVAL,
V_CUST_ID,
P_PAYMENT_TYPE,
P_CARD_TYPE,
--TO_CHAR(P_CARD_EXPIRY_DATE, 'MM/RR'),
V_CARD_EXPRIRY_dATE,
SYSDATE,
'SUCCESS',
ORA_HASH(P_CARD_NUMBER)
);
commit;
ELSE
DBMS_OUTPUT.PUT_LINE ('The Payment method is not accepted');
end if;
EXCEPTION WHEN OTHERS
THEN
            dbms_output.put_line('Please correct the following error - ' || SQLERRM);
END;